name: Run get_new_results.py daily

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the Python script
        run: |
          python data_process_scripts/get_new_results.py

      - name: Clone private repository
        run: |
          git clone https://x-access-token:${{ secrets.PRIVATE_REPO_PAT }}@github.com/YourUsername/your-private-repo.git private_repo

      - name: Copy results to private repository
        run: |
          cp -r path/to/generated/files/* private_repo/path/to/target/

      - name: Commit and push to private repository
        run: |
          cd private_repo
          git config user.name "colemanferrell2"
          git config user.email "caferr@unc.edu"
          git add -A
          git commit -m "Auto-update from GitHub Action" || echo "No changes to commit"
          git push
