name: Update athlete-metadata folder

on:
  schedule:
    - cron: "0 7 * * *"  # Runs daily at 3AM ET / 7AM UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  update-athlete-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run get_new_results.py
        run: python data_process_scripts/get_new_results.py

      - name: Clone private repository
        run: |
          git clone https://x-access-token:${{ secrets.PRIVATE_REPO_PAT }}@github.com/colemanferrell2/Runner-Recruiting-Resource.git private_repo

      - name: Remove existing athlete-metadata folder
        run: |
          cd private_repo
          git rm -rf data_process_scripts/athlete-metadata || echo "Folder already removed or missing"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Remove old athlete-metadata" || echo "Nothing to commit"

      - name: Copy new athlete-metadata files
        run: |
          mkdir -p private_repo/data_process_scripts/
          cp -r data_process_scripts/athlete-metadata private_repo/data_process_scripts/

      - name: Commit and push in chunks
        run: |
          cd private_repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          find data_process_scripts/athlete-metadata -type f > files_to_commit.txt
          split -l 250 files_to_commit.txt chunk_

          for chunk in chunk_*; do
            xargs -a "$chunk" git add
            git commit -m "Update athlete-metadata chunk" || echo "No changes in this chunk"
          done

          git push https://x-access-token:${{ secrets.PRIVATE_REPO_PAT }}@github.com/colemanferrell2/Runner-Recruiting-Resource.git HEAD:main

          # Cleanup chunk files
          rm chunk_* files_to_commit.txt

      - name: Trigger assign_scores workflow in private repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.CROSS_REPO_PAT }}" \
            https://api.github.com/repos/colemanferrell2/Runner-Recruiting-Resource/dispatches \
            -d '{"event_type": "run-assign-scores"}'
