name: Update athlete-metadata folder

on:
  schedule:
    - cron: "0 7 * * *"  # Daily at 3AM ET / 7AM UTC
  workflow_dispatch:

jobs:
  get-new-results:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.timestamp.outputs.now }}
    steps:
      - name: Checkout public repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Updated to match your script's requirements

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect initial data
        run: python data_process_scripts/get_new_results.py --mode collect  # Added mode

      - name: Save timestamp
        id: timestamp
        run: echo "now=$(date +%s)" >> $GITHUB_OUTPUT

  fetch-athletes:
    needs: get-new-results
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Updated version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Process shard ${{ matrix.shard }}
        run: python data_process_scripts/get_new_results.py --mode process --shard ${{ matrix.shard }} --num_shards 20  # Added mode

  push-athletes:
    needs: fetch-athletes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repository
        uses: actions/checkout@v4

      - name: Clone private repository
        run: |
          git clone https://x-access-token:${{ secrets.PRIVATE_REPO_PAT }}@github.com/colemanferrell2/Runner-Recruiting-Resource.git private_repo

      - name: Remove existing athlete-metadata folder
        run: |
          cd private_repo
          git rm -rf data_process_scripts/athlete-metadata || echo "Folder already removed or missing"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Remove old athlete-metadata" || echo "Nothing to commit"

      - name: Copy new athlete-metadata files
        run: |
          mkdir -p private_repo/data_process_scripts/
          cp -r data_process_scripts/athlete-metadata private_repo/data_process_scripts/

      - name: Commit and push in chunks
        run: |
          cd private_repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          find data_process_scripts/athlete-metadata -type f > files_to_commit.txt
          split -l 250 files_to_commit.txt chunk_

          for chunk in chunk_*; do
            xargs -a "$chunk" git add
            git commit -m "Update athlete-metadata chunk" || echo "No changes in this chunk"
          done

          git push https://x-access-token:${{ secrets.PRIVATE_REPO_PAT }}@github.com/colemanferrell2/Runner-Recruiting-Resource.git HEAD:master

          rm chunk_* files_to_commit.txt

      - name: Trigger assign_scores workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PRIVATE_REPO_PAT }}" \
            https://api.github.com/repos/colemanferrell2/Runner-Recruiting-Resource/dispatches \
            -d '{"event_type": "run-assign-scores"}'
